### ISSUE TITLE
Can't use delombok with lombok 1.16.10

### ISSUE THREAD

**Issue by pillisan42** [franzbecker/gradle-lombok#11]
Hi ! 

I think they have changed some thing in the latest version of lombok when i use "gradle delombok" task i've got the following exception (btw it work well with lombok 1.16.4) : 
Exception in thread "main" com.sun.tools.javac.processing.AnnotationProcessingError: java.lang.ClassCastException: Cannot cast lombok.javac.handlers.HandleFieldDefaults to lombok.javac.JavacASTVisitor
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:520)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
        at lombok.delombok.Delombok.delombok(Delombok.java:503)
        at lombok.delombok.Delombok.main(Delombok.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lombok.delombok.DelombokApp.runApp(DelombokApp.java:55)
        at lombok.core.Main.go(Main.java:128)
        at lombok.core.Main.main(Main.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lombok.launch.Main.main(Main.java:36)
Caused by: java.lang.ClassCastException: Cannot cast lombok.javac.handlers.HandleFieldDefaults to lombok.javac.JavacASTVisitor
        at java.lang.Class.cast(Class.java:3369)
        at lombok.core.SpiLoadUtil$1$1.next(SpiLoadUtil.java:111)
        at lombok.javac.HandlerLibrary.loadVisitorHandlers(HandlerLibrary.java:184)
        at lombok.javac.HandlerLibrary.load(HandlerLibrary.java:156)
        at lombok.javac.JavacTransformer.<init>(JavacTransformer.java:43)
        at lombok.javac.apt.Processor.init(Processor.java:86)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        ... 21 more

**Comment by franzbecker** [comment]
Based on your description it's not possible for me to reproduce the issue.
I ran the integration tests of this plugin with the version 1.16.10 and everything seems fine.

Have you tried calling delombok manually (https://projectlombok.org/features/delombok.html)?
Maybe it's an issue of Lombok itself and not this plugin.

**Comment by bensullivan** [comment]
Hi Franz

I have reproduced this exception in a very simple project here:

https://github.com/bensullivan/gradle-lombok-issue/commits/master

It appears as though there is a problem in Lombok with having multiple dependencies in the gradle cache.

Your plugin appears to depend on Lombok 1.16.4.  In the initial commit of my basic sandpit project I can run delombok ok through gradle which resolves 1.16.4.

However, if I declare a later version of Lombok (see second commit) then this exception results when I run the same ./gradlew delombok command.  Is there any way to remove the hard dependency on 1.16.4 from your plugin?

I will go with 1.16.4 for now.

Thanks

Ben

**Comment by franzbecker** [comment]
Hi Ben,

thanks for taking the time to extract the problem. The issue here is that you added the Lombok dependency explicitly:

```
dependencies {
    compile(
            'org.projectlombok:lombok:1.16.12'
    )
}
```

The plugin itself adds the dependency so in the end you will have it twice, as you already observed.
Also, if you add the dependency in the compile scope, your project will be dependent on Lombok during runtime, which you probably don't want.

Can you try removing the explicit dependency?

**Comment by bensullivan** [comment]
Hi Franz

Happy New Year!

Thanks for the prompt reply.

Yes I realised that was the case and I am currently operating as you suggest.  My question is how do I use your plugin and have my project depend on a specific version of Lombok rather than being locked in to 1.16.4?

Thanks

Ben

**Comment by franzbecker** [comment]
Hi Ben,

thanks happy new year to you as well!

You can use a different Lombok version by putting the following block into your build.gradle:

```
lombok {
    version = "1.16.12"
    sha256 = "" // skip verifyLombok task or sha256 here
}
```
