### ISSUE TITLE
NoClassDefFoundError: Lombok dependency w/ JDK 11 fails/absent when running tests

### ISSUE THREAD

**Issue by mmoayyed** [franzbecker/gradle-lombok#50]
## Problem

Using JDK 11-ea and Gradle 4.9 and the latest version of this plugin at this time `1.14`, Gradle fails to run tests complaining about missing Lombok classes.

## How

Full error output:
https://travis-ci.org/apereo/cas/jobs/416457613

I see the following failure when Gradle begins to run tests:

```
> Task :core:cas-server-core-authentication:test

org.apereo.cas.authentication.FileTrustStoreSslSocketFactoryTests > verifyTrustStoreBadPassword FAILED
    java.lang.AssertionError: 
    Expected: an instance of java.io.IOException
         but: <java.lang.NoClassDefFoundError: lombok/Lombok> is a java.lang.NoClassDefFoundError
    Stacktrace was: java.lang.NoClassDefFoundError: lombok/Lombok
    	at org.apereo.cas.authentication.DefaultCasSslContext.<init>(DefaultCasSslContext.java:47)
    	at org.apereo.cas.authentication.FileTrustStoreSslSocketFactoryTests.sslFactory(FileTrustStoreSslSocketFactoryTests.java:37)
    	at org.apereo.cas.authentication.FileTrustStoreSslSocketFactoryTests.verifyTrustStoreBadPassword(FileTrustStoreSslSocketFactoryTests.java:69)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
    	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    	at jdk.internal.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
    	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.ClassNotFoundException: lombok.Lombok
    	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
    	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    	... 50 more
```

## Possible Solution(?)

As an experiment, I added the following to the build:

```
testImplementation "org.projectlombok:lombok:$lombokVersion"
```

...and the issue _seems_ to have disappeared. While other things continue to fail, it seems like the lombok dependency is expected for tests as well?

Here is a more recent version of the build:
https://travis-ci.org/apereo/cas/jobs/418577491

...where you might note that the test is no longer failing on a missing class. It does, however, fail for different reasons but the above change seems to have caught the `ClassNotFoundException` error.

If you consider the above change to be reasonable, I'd be happy to submit a pull request and include the dependency for tests.

**Comment by franzbecker** [comment]
Hm interesting. I think Gradle didn't even announce Java 11 support yet ;)
I think `testImplementation` would not be the best scope - Lombok is an annotation processor and should not be available during runtime. Currently it is added to the `compileOnly` and `testCompileOnly` scope and the corresponding annotation processor scopes as well, see: 
https://github.com/franzbecker/gradle-lombok/blob/1c4c2872a3695d5cad2c26b0f38059692ae1a15d/src/main/groovy/io/franzbecker/gradle/lombok/LombokPlugin.groovy#L41-L50

Would be nice to narrow it down a bit but I would wait until Gradle announces JDK 11 support.

**Comment by mmoayyed** [comment]
Thank you for the follow-up. I believe Gradle's support for JDK 11 is blocked by this issue: https://github.com/gradle/gradle/issues/5120 which is something that depends on a Groovy release. Should hopefully happen in a week or two.

**Comment by franzbecker** [comment]
I've tested it with JDK 11 and Lombok 1.18.4 - seems to be working just fine. I'll publish a new version that uses Lombok 1.18.4 by default very soon.
