### ISSUE TITLE
Quarkus reload fails every time with lombok / gradle-lombok plugin

### ISSUE THREAD

**Issue by ieugen** [franzbecker/gradle-lombok#75]
Hello,

This might be a quarkus issue but with gradle, the reload issue happens all the time. 

```
    ^
  	at lombok.javac.apt.LombokProcessor.getJavacProcessingEnvironment(LombokProcessor.java:419)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:90)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:124)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:177)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:73)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:508)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:605)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discov
```

https://github.com/quarkusio/quarkus/issues/4224

**Comment by franzbecker** [comment]
Hi @ieugen, is this still an issue for you?

**Comment by franzbecker** [comment]
Closing as author moved to Clojure https://github.com/franzbecker/gradle-lombok/issues/65#issuecomment-626323128
